# Generated by Django 4.2.6 on 2023-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='position',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='prise',
            field=models.CharField(max_length=255),
        ),
    ]
